#!/usr/bin/env python

import tullius
import logging

logger = logging.getLogger('tullius')
logger.setLevel(logging.INFO)
fh = logging.FileHandler('/var/log/tullius.log')
fh.setLevel(logging.INFO)
logger.addHandler(fh)

tullius.daemon()
